### ISSUE TITLE
Failed to load file "xxx.mp3". Resource does not exist.

### ISSUE THREAD

**Issue by Slexxxx** [rednblackgames/gdx-miniaudio#7]
I`m trying to load a sound file via AssetManager:

```//music
        am.setLoader(MASound.class, new MASoundLoader(miniAudio,  new InternalFileHandleResolver()));
        //setupAndroid(am.getAssetFileName("sounds/Dark_Ambient_Cave.mp3"));

        am.load("sounds/Dark_Ambient_Cave.mp3" , MASound.class);
        //am.load("F:\\xxx\\assets\\sounds\\Dark_Ambient_Cave.mp3" , MASound.class);

        am.finishLoading();

        MASound maSound =  am.get("sounds/Dark_Ambient_Cave.mp3"  , MASound.class);
        //MASound maSound =  am.get("F:\\xxx\\assets\\sounds\\Dark_Ambient_Cave.mp3"  , MASound.class);
        maSound.setVolume(VOLUME_MUSIC);
        maSound.play();
```

and get this Error in line "am.finishLoading()":
```[GdxMiniAudio] Failed to load file "sounds/Dark_Ambient_Cave.mp3". Resource does not exist.

Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: sounds/Dark_Ambient_Cave.mp3
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:648)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:426)
	at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:455)
```

if i load the sound file with absolute path, all is fine:
```//music
        am.setLoader(MASound.class, new MASoundLoader(miniAudio,  new InternalFileHandleResolver()));
        //miniAudio.setupAndroid(am.getAssetFileName("sounds/Dark_Ambient_Cave.mp3"));

        //am.load("sounds/Dark_Ambient_Cave.mp3" , MASound.class);
        am.load("F:\\xxx\\assets\\sounds\\Dark_Ambient_Cave.mp3" , MASound.class);

        am.finishLoading();

        //MASound maSound =  am.get("sounds/Dark_Ambient_Cave.mp3"  , MASound.class);
        MASound maSound =  am.get("F:\\xxx\\assets\\sounds\\Dark_Ambient_Cave.mp3"  , MASound.class);
        maSound.setVolume(VOLUME_MUSIC);
        maSound.play();
```

**Comment by fgnm** [comment]
Hi, looks like you're hitting the #2 , Since miniaudio is a native library can't directly access resources in a jar file, so depending how you've setup your dev environment `InternalFileHandleResolver` could point to some directory which isn't probably the assets folder. Of course you can setup the dev environment to get it working with relatives path, but once exported it will not work on desktop. As the other user suggested, there could be a workaround to not force the unzipping from jar and load with absolute paths, but haven't had the time to work on it yet. 
BTW this is a desktop-only issue, mobile works differently there are no issues working with assets there

**Comment by lucas-viva** [comment]
@fgnm is reading sound files from resources in jar files still a limitation on desktop? Or has this changed?

**Comment by fgnm** [comment]
@lucas-viva yes and no. The technical limitation is clear: miniaudio is a C native library, resources are packed into a zip/jar archive which the library cannot access easily. You have two options:

1. Extract resources into temp or installation directory with Java, and load them from path.
2. Read full bytes into memory and go with the RAM (ref. https://github.com/rednblackgames/gdx-miniaudio/issues/2#issuecomment-4412967240 and https://github.com/rednblackgames/gdx-miniaudio/commit/a5dfe8548a62d8a134a421551d360516d7b694ff).

On the second point you'll loose the streaming flag benefit because the bytes will be loaded in memory anyway, and you'll also loose also the sound length due to a miniaudio missing implementation (ref. #20).
Currently, this is the only tradeoff of this library. If you have suggestions on how a native C code can read directly JVM resources, feel free to suggest a new issue or PR, but last time I checked was not that easy and quite out of the scope of the library
